AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda functions to provision Greengrass resources with CloudFormation'

Resources:

  GrassFormationFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: GrassFormationFunctionExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'greengrass:*'
                  - 'iam:PassRole'
                Resource: '*'

  # Exported functions

  GroupHandlerFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.group_handler
      Code: grassformation
      Role: !GetAtt [ GrassFormationFunctionRole, Arn ]
      MemorySize: 128
      Timeout: 3
      Runtime: python3.6

  CoreHandlerFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.core_handler
      Code: grassformation
      Role: !GetAtt [ GrassFormationFunctionRole, Arn ]
      MemorySize: 128
      Timeout: 3
      Runtime: python3.6

  ResourceHandlerFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.resource_handler
      Code: grassformation
      Role: !GetAtt [ GrassFormationFunctionRole, Arn ]
      MemorySize: 128
      Timeout: 3
      Runtime: python3.6

  LoggerHandlerFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.logger_handler
      Code: grassformation
      Role: !GetAtt [ GrassFormationFunctionRole, Arn ]
      MemorySize: 128
      Timeout: 3
      Runtime: python3.6

  SubscriptionHandlerFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.subscription_handler
      Code: grassformation
      Role: !GetAtt [ GrassFormationFunctionRole, Arn ]
      MemorySize: 128
      Timeout: 3
      Runtime: python3.6

  FunctionHandlerFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.function_handler
      Code: grassformation
      Role: !GetAtt [ GrassFormationFunctionRole, Arn ]
      MemorySize: 128
      Timeout: 3
      Runtime: python3.6

  DeviceHandlerFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.device_handler
      Code: grassformation
      Role: !GetAtt [ GrassFormationFunctionRole, Arn ]
      MemorySize: 128
      Timeout: 3
      Runtime: python3.6

  DispatchHandlerFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.dispatch_handler
      Code: grassformation
      Role: !GetAtt [ GrassFormationFunctionRole, Arn ]
      MemorySize: 128
      Timeout: 3
      Runtime: python3.6

# CloudFormation transform macro

  MacroFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: macro.handler
      Code: grassformation
      Environment:
        Variables:
          DISPATCH_HANDLER_LAMBDA_ARN: !GetAtt DispatchHandlerFunction.Arn
      Role: !GetAtt [ GrassFormationFunctionRole, Arn ]
      MemorySize: 128
      Timeout: 3
      Runtime: python3.6

  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: GrassFormation
      FunctionName: !GetAtt MacroFunction.Arn

  MacroFunctionPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt MacroFunction.Arn
      Principal: 'cloudformation.amazonaws.com'

  MacroFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ['logs:*']
                Resource: 'arn:aws:logs:*:*:*'

Outputs:

  GroupHandlerFunctionArn:
    Description: The ARN of the lambda function handling Greengrass Group resources.
    Value: !GetAtt GroupHandlerFunction.Arn
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "GroupHandlerFunctionArn"]]

  CoreHandlerFunctionArn:
    Description: The ARN of the lambda function handling Greengrass Core resources.
    Value: !GetAtt CoreHandlerFunction.Arn
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "CoreHandlerFunctionArn"]]

  ResourceHandlerFunctionArn:
    Description: The ARN of the lambda function handling Greengrass Resource resources.
    Value: !GetAtt ResourceHandlerFunction.Arn
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "ResourceHandlerFunctionArn"]]

  LoggerHandlerFunctionArn:
    Description: The ARN of the lambda function handling Greengrass Logger resources.
    Value: !GetAtt LoggerHandlerFunction.Arn
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "LoggerHandlerFunctionArn"]]

  SubscriptionHandlerFunctionArn:
    Description: The ARN of the lambda function handling Greengrass Subscription resources.
    Value: !GetAtt SubscriptionHandlerFunction.Arn
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "SubscriptionHandlerFunctionArn"]]

  FunctionHandlerFunctionArn:
    Description: The ARN of the lambda function handling Greengrass Function resources.
    Value: !GetAtt FunctionHandlerFunction.Arn
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "FunctionHandlerFunctionArn"]]

  DeviceHandlerFunctionArn:
    Description: The ARN of the lambda function handling Greengrass Device resources.
    Value: !GetAtt DeviceHandlerFunction.Arn
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "DeviceHandlerFunctionArn"]]

  DispatchHandlerFunctionArn:
    Description: The ARN of the lambda function handling all Greengrass resources.
    Value: !GetAtt DispatchHandlerFunction.Arn
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "DispatchHandlerFunctionArn"]]
