service: grassformation

provider:
  name: aws
  runtime: python3.6

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "greengrass:*"
     Resource: "*"

functions:
  group:
    handler: group.handler
  core:
    handler: core.handler
  resource:
    handler: resource.handler
