service: grassformation

provider:
  name: aws
  runtime: python3.6

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "greengrass:*"
     Resource: "*"

functions:
  group:
    handler: grassformation.group.handler
  core:
    handler: grassformation.core.handler
  resource:
    handler: grassformation.resource.handler
