service: grassformation

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "greengrass:*"
       - "iam:PassRole"
     Resource: "*"

custom:
  stage: ${opt:stage, self:provider.stage}

functions:
  GroupHandler:
    handler: grassformation.group.handler
  CoreHandler:
    handler: grassformation.index.core_handler
  ResourceHandler:
    handler: grassformation.index.resource_handler
  LoggerHandler:
    handler: grassformation.index.logger_handler
  SubscriptionHandler:
    handler: grassformation.index.subscription_handler
  FunctionHandler:
    handler: grassformation.index.function_handler
  DeviceHandler:
    handler: grassformation.index.device_handler

resources:
  Outputs:
    GroupHandlerLambdaFunctionArn:
      Description: The ARN of the lambda function handling Greengrass Group resources.
      Value: { "Fn::GetAtt": ["GroupHandlerLambdaFunction", "Arn" ] }
      Export:
        Name: "${self:service}-${self:custom.stage}-GroupHandlerLambdaFunctionArn"
    CoreHandlerLambdaFunctionArn:
      Description: The ARN of the lambda function handling Greengrass Core resources.
      Value: { "Fn::GetAtt": ["CoreHandlerLambdaFunction", "Arn" ] }
      Export:
        Name: "${self:service}-${self:custom.stage}-CoreHandlerLambdaFunctionArn"
    ResourceHandlerLambdaFunctionArn:
      Description: The ARN of the lambda function handling Greengrass Resource resources.
      Value: { "Fn::GetAtt": ["ResourceHandlerLambdaFunction", "Arn" ] }
      Export:
        Name: "${self:service}-${self:custom.stage}-ResourceHandlerLambdaFunctionArn"
    LoggerHandlerLambdaFunctionArn:
      Description: The ARN of the lambda function handling Greengrass Logger resources.
      Value: { "Fn::GetAtt": ["LoggerHandlerLambdaFunction", "Arn" ] }
      Export:
        Name: "${self:service}-${self:custom.stage}-LoggerHandlerLambdaFunctionArn"
    SubscriptionHandlerLambdaFunctionArn:
      Description: The ARN of the lambda function handling Greengrass Subscription resources.
      Value: { "Fn::GetAtt": ["SubscriptionHandlerLambdaFunction", "Arn" ] }
      Export:
        Name: "${self:service}-${self:custom.stage}-SubscriptionHandlerLambdaFunctionArn"
    FunctionHandlerLambdaFunctionArn:
      Description: The ARN of the lambda function handling Greengrass Function resources.
      Value: { "Fn::GetAtt": ["FunctionHandlerLambdaFunction", "Arn" ] }
      Export:
        Name: "${self:service}-${self:custom.stage}-FunctionHandlerLambdaFunctionArn"
    DeviceHandlerLambdaFunctionArn:
      Description: The ARN of the lambda function handling Greengrass Device resources.
      Value: { "Fn::GetAtt": ["DeviceHandlerLambdaFunction", "Arn" ] }
      Export:
        Name: "${self:service}-${self:custom.stage}-DeviceHandlerLambdaFunctionArn"
